config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  
  resources :tasks
  resources :users, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: {maximum: 255}
  validates :status, presence: true, length: {maximum: 10}
  validates :user, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  # Userインスタンス(レコード)を保存する前に文字を全て小文字に変換する
  before_save {self.email.downcase!}
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                    uniqueness: {case_sensitive: false}
  
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private
  # ログイン要求処理
  def require_user_logged_in
  # true current_userにログインユーザの情報が入り処理は実行されない,false unlessメソッドが実行され強制的にログイン画面に飛ばされる
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

# sessions#create が実質的なログイン処理を担当
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = "ログインに成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] ="ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # 下記コードでこの中の全アクションがログイン必須
  before_action :require_user_logged_in
  # correct_user 現時点ではdestroyのみが定義されている状態,ここに詳細,編集,更新を追加
  before_action :correct_user, only: [:destroy, :show, :edit, :update]
  
  # tasks#index
  def index
      @pagy, @tasks = pagy(current_user.tasks.order(id: :desc))
  end
  
  # tasks#show
  def show
  end
  
  # tasks#new
  def new
    @task = current_user.tasks.build
  end
  
  # task#create
  def create
    @task = current_user.tasks.build(task_params)
      if @task.save
        flash[:success] = "Task を投稿しました。"
        redirect_to root_url
      else
        @pagy, @tasks = pagy(current_user.tasks.order(id: :desc))
        flash.now[:danger] = "Task の投稿に失敗しました。"
        render "tasks/new"
      end
  end
    
  # tasks#edit
  def edit
  end
  
  # tasks#update
  def update
    if @task.update(task_params)
      flash[:success] = "Task は正常に更新されました"
      redirect_to @task
    else
      flash.now[:danger] = "Task は更新されませんでした"
      render :edit
    end
  end
  
  # task#destroy
  def destroy
    @task.destroy
    
    flash[:success] = "Task は正常に削除されました"
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status, :user)
  end
  
  # ログインユーザーのみがCRUD操作を行えるようになるメソッド
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "ユーザの登録に失敗しました。"
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 現在ログインしているユーザを取得するメソッド
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # ユーザがログインしていればtrue,ログインしていなければfalseを返す
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Tasklist</a>
      <button class="navbar-toggler" type="button" data-bs-topple="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <!--ログインしている時に表示される-->
        <% if logged_in? %>
          <div class="btn-group">
            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to "Logout", logout_path, method: :delete, class:"nav-link" %></li>
            </ul>
          </div>
        <!--ログインしていない時に表示される-->
        <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Signup", signup_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", login_path, class:"nav-link" %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render "layouts/flash_messages" %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task) do |f| %>
  <div id="error_explanation">
    <% if task.errors.any? %>
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
   
    <% end %>
  
    <%= f.label :status, "ステータス" %>
    <%= f.text_field :status %>
    
    <%= f.label :content, "タスク" %>
    <%= f.text_field :content %>
    
    <%= f.submit "投稿" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/index.html.erb
<% if @tasks.any? %>
 <ul class="list-unstyled mt-2">
   <% @tasks.each do |task| %>
     <li class="d-flex">
       <img class="rounded me-2 mb-5" src="<%= gravatar_url(task.user,{size:64}) %>" alt="">
       <div>
         <div>
          <!--ログインユーザ名:投稿日時-->
           <p><%= task.user.name %> : posted at <%= task.created_at %></p>
           <!--投稿内容-->
           <p><%= task.content %></p>
         </div>
         <div>
          <!--ログインユーザと投稿ユーザが一緒ならば-->
           <% if current_user == task.user %>
            <%= link_to "詳細", task, method: :get, class: "btn btn-success btn-sm" %>
            <%= link_to "削除", task, method: :delete, data: {confirm: "You sure?"}, class: "btn btn-danger btn-sm" %>
           <% end %>
         </div>
       </div>
     </li>
   <% end %>
 </ul>
 <%== pagy_bootstrap_nav(@pagy) %>
<% end %>
<%= link_to "新規タスクの投稿", new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<!--投稿したタスクの詳細ページ-->
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>

<p>ステータス: <%= @task.status %></p>
<p>コンテンツ: <%= @task.content %></p>

<%= link_to "一覧に戻る", tasks_path %>
<%= link_to "このタスクを編集する", edit_task_path(@task) %>
<!--<%= link_to "このタスクを削除する", @task, method: :delete, data: {confirm:"本当に削除してもよろしいですか？"} %>-->

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>
  
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
    <div class="mb-3">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <div class="mb-3">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class:"form-control" %>
    </div>
    
    <div class="mb-3">
      <%= f.label :password, "Password" %>
      <%= f.password_field :password, class:"form-control" %>
    </div>
    
    <div class="mb-3">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class:"form-control" %>
    </div>
    
    <%= f.submit "Sign up", class: "btn btn-primary w-100" %>
    <% end %>
  </div>
</div>